### ISSUE TITLE
Exception in thread EDAutopilot:

### ISSUE THREAD

**Issue by mrfisse** [TomW1605/EDAutopilot#4]
Getting this error while activating the program. Using a fresh python 3.6.0 install.

Exception in thread EDAutopilot:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\EDAutopilot\dev_autopilot.py", line 1008, in autopilot
    align()
  File "D:\EDAutopilot\dev_autopilot.py", line 803, in align
    off = get_navpoint_offset()
  File "D:\EDAutopilot\dev_autopilot.py", line 631, in get_navpoint_offset
    filtered = filter_blue(compass_image)
  File "D:\EDAutopilot\dev_autopilot.py", line 557, in filter_blue
    hsv = cv2.cvtColor(hsv, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by TomW1605** [comment]
can you answer a few questions:
1. do you have 2 screens?
2. what is your screens native resolution?
3. what res are you running at?
4. is the game full screen (or full screen windowed)?
5. any other details you can add

could you also send your logs. there should be a file called `EDAutopilot.log`

**Comment by TomW1605** [comment]
also can you confirm that you are using the master branch and not my development branch?

**Comment by mrfisse** [comment]
Sure thing !
1. Nope only one plus my Valve Index but that is not hooked up while using this program.
2.My native res is 2560x1440.
3.Tried 1920x1080 and 2560x1440
4.When i tried this I used set the game to borderless 
5. Only screen related stuff I have is DisplayCal forcing my screen calibration.

Will give you a fresh log when I come home but if I remember correctly the log does not mention the error I see in the console.

**Comment by TomW1605** [comment]
thanks for all that. that all looks normal. i don't think DisplayCal would be messing with resolution but it might be breaking the screenshots. could you try with it off and see if it changes? i doubt the logs will mention the crash however it will be helpful to see what it was doing when it did crash.

**Comment by TomW1605** [comment]
@mrfisse were you able to get the log file?
